/**
 * Trading Terminal (trading) skin hooks - DRAFT generated by scripts/dsh-skin-migrate-v2.mjs.
 *
 * TODO: manual review required before this file ships (issue #506). This
 * is a scaffold, not a verified port: read every TODO below, test against
 * the skin-center hooks runtime (contract x-org.linxin666.skin-center/v1alpha1),
 * then delete this header comment.
 *
 * Auto-migrated by the codemod (no hook code needed):
 *  - stylesheet scoping -> html[data-dsh-skin="trading"] (loader-owned);
 *    the v1 body attribute is never written by v2 skins.
 *
 * TODO manual port:
 *  1. a link element is injected (favicon or stylesheet); port it to hooks or drop it
 */

export default function defineSkinHooks() {
  return {
    apply(ctx) {
      // TODO(review): port the v1 effects listed in the header.
      void ctx
    },
  }
}
