/**
 * Dragon Heir (dragon-heir) skin hooks - DRAFT generated by scripts/dsh-skin-migrate-v2.mjs.
 *
 * TODO: manual review required before this file ships (issue #506). This
 * is a scaffold, not a verified port: read every TODO below, test against
 * the skin-center hooks runtime (contract x-org.linxin666.skin-center/v1alpha1),
 * then delete this header comment.
 *
 * Auto-migrated by the codemod (no hook code needed):
 *  - backdrop artwork + light/dark readability scrims ->
 *    contributes.backgroundMedia in skin.json. The skin-center owns the
 *    theme switch and the background-occlusion control now; the v1
 *    MutationObserver scrim swap is intentionally dropped.
 *  - stylesheet scoping -> html[data-dsh-skin="dragon-heir"] (loader-owned);
 *    the v1 body attribute is never written by v2 skins.
 *
 * TODO manual port:
 *  1. a link element is injected (favicon or stylesheet); port it to hooks or drop it
 *  2. inlined image constant(s) DARK_ART are referenced from JS-built CSS; extract them to assets/ and rewrite the URLs by hand
 */

export default function defineSkinHooks() {
  return {
    apply(ctx) {
      // TODO(review): port the v1 effects listed in the header.
      void ctx
    },
  }
}
