/**
 * Abyssal Maid Atelier (maid-atelier) skin hooks - DRAFT generated by scripts/dsh-skin-migrate-v2.mjs.
 *
 * TODO: manual review required before this file ships (issue #506). This
 * is a scaffold, not a verified port: read every TODO below, test against
 * the skin-center hooks runtime (contract x-org.linxin666.skin-center/v1alpha1),
 * then delete this header comment.
 *
 * Auto-migrated by the codemod (no hook code needed):
 *  - stylesheet scoping -> html[data-dsh-skin="maid-atelier"] (loader-owned);
 *    the v1 body attribute is never written by v2 skins.
 *
 * TODO manual port:
 *  1. favicon injection - drafted below from the v1 bundle constant;
 *     verify the asset URL base (ctx.assetBase) and the replace/restore
 *     semantics against any pre-existing favicon link.
 *  2. the v1 bundle builds extra stylesheet(s) in JS (template literals with interpolated assets); port them to patches.css with relative asset URLs or to hooks code
 *  3. canvas / animation-frame effect detected (e.g. ambient overlay); port it to hooks using ctx.layers (all layers are pointer-events:none)
 *  4. MutationObserver logic detected; decide what it watched (theme flips are covered by backgroundMedia light/dark) and port the rest
 *  5. inlined image constant(s) MAID_ATELIER_CHIBI, MAID_ATELIER_BOW_CLEAN, MAID_ATELIER_NEW_SESSION, MAID_ATELIER_SIDEBAR_SWAG, MAID_ATELIER_TOP_TRIM_TILE, MAID_ATELIER_PALACE_LIGHT, MAID_ATELIER_PALACE_DARK, MAID_ATELIER_MAID_LEFT, MAID_ATELIER_MAID_RIGHT, MAID_ATELIER_BOTTOM_TRIM_TILE, MAID_ATELIER_BOTTOM_CREST, MAID_ATELIER_SIDEBAR_CORNER, MAID_ATELIER_COMPOSER_FRAME, MAID_ATELIER_SETTINGS_FRAME, MAID_ATELIER_WORKSPACE_SHIELD, MAID_ATELIER_WORKSPACE_RIBBON are referenced from JS-built CSS; extract them to assets/ and rewrite the URLs by hand
 */

export default function defineSkinHooks() {
  return {
    apply(ctx) {
      // TODO(review): favicon port. v1 injected a <link rel="icon"> with an
      // inline SVG; the codemod extracted it to assets/maid-atelier-icon.webp.
      const favicon = document.createElement('link')
      favicon.rel = 'icon'
      favicon.type = 'image/svg+xml'
      favicon.href = ctx.assetBase + '/assets/maid-atelier-icon.webp'
      document.head.append(favicon)
      ctx.onCleanup(() => favicon.remove())
    },
  }
}
